# Home Work 01
1. Numpy
1. Pytorch (tensor (basic operations))

# DEADLINE

### IS-142 - 08.10.24
### IS-141 - 15.10.24

## BLOKE №1 (numpy)

1. Импортировать NumPy под именем np

In [31]:
import numpy as np

2. Создать вектор (одномерный массив) размера 20, заполненный нулями

In [32]:
vec = np.zeros(20)
vec

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


3. Создать вектор размера 20, заполненный числом 1.75

In [33]:
vec1 = np.full(20,1.75)
vec1

[1.75 1.75 1.75 1.75 1.75 1.75 1.75 1.75 1.75 1.75 1.75 1.75 1.75 1.75
 1.75 1.75 1.75 1.75 1.75 1.75]


4. Создать вектор со значениями от 4 до 31

In [34]:
vec3 = np.arange(4,32,1)
vec3

[ 4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27
 28 29 30 31]


5. Развернуть вектор (первый становится последним)

In [81]:
vec4 = np.flip(vec3)
vec4

array([31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16, 15,
       14, 13, 12, 11, 10,  9,  8,  7,  6,  5,  4])

6. Создать матрицу (двумерный массив) 3x3 со значениями от 1 до 9

In [82]:
matrix = np.arange(1,10,1).reshape(3,3)
matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

7. Создать 3x3 единичную матрицу

In [83]:
matrix1 = np.eye(3)
matrix1

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

8. Создать 4x4 пустую матрицу

In [38]:
matrix2 = np.empty((4,4))
matrix2

[[6.73222589e-316 0.00000000e+000 2.41907520e-312 2.14321575e-312]
 [2.46151512e-312 2.31297541e-312 2.35541533e-312 2.05833592e-312]
 [2.22809558e-312 2.56761491e-312 2.48273508e-312 2.05833592e-312]
 [2.05833592e-312 2.29175545e-312 2.07955588e-312 2.14321575e-312]]


9. Создать единичную матрицу 4x4 со сдвигом на единицу вниз относительно главной диагонали

In [84]:
matrixeye = np.eye(4,4,-1)
matrixeye

array([[0., 0., 0., 0.],
       [1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

10. Создать тензор 3x3x3 со случайными значениями

In [40]:
tens = np.random.random((3,3,3))
tens

[[[0.26271507 0.09085085 0.01358005]
  [0.16386482 0.233183   0.51716871]
  [0.19210831 0.66396652 0.53152115]]

 [[0.03302616 0.31145297 0.16481337]
  [0.85818534 0.40441831 0.17153889]
  [0.85197807 0.39345899 0.36911737]]

 [[0.81992512 0.29795091 0.93003611]
  [0.55717784 0.01627998 0.88546973]
  [0.52500313 0.14356999 0.93865641]]]


11. Создать массив 5x5 со случайными значениями, найти минимум и максимум

In [90]:
array = np.random.random((5,5))
print(array)
print(np.min(array))
np.max(array)

[[0.94782533 0.03820325 0.42107683 0.82604854 0.82248414]
 [0.01312328 0.58810351 0.75182615 0.39901555 0.14746326]
 [0.46234494 0.2033741  0.72833177 0.5300169  0.53520071]
 [0.13360384 0.89581117 0.31892267 0.69114583 0.63535246]
 [0.72349517 0.55294558 0.44066363 0.12173857 0.3492321 ]]
0.013123281916936347


0.9478253258699243

12. Создать случайный вектор размера 50 и найти среднее значение всех элементов

In [91]:
vec5 = np.random.random(50)
print(vec5)
np.mean(vec5)

[0.96199544 0.4655379  0.20906053 0.81394864 0.29655252 0.97779804
 0.27517394 0.57344409 0.70728659 0.04211742 0.74087931 0.92587402
 0.87898185 0.3870126  0.57006386 0.44090537 0.83190672 0.26923777
 0.40571178 0.56411201 0.74641041 0.37462466 0.68225293 0.03100854
 0.73339119 0.29312149 0.87358798 0.12866233 0.43945663 0.12043822
 0.26943604 0.19472944 0.07707306 0.28608455 0.15980506 0.27071434
 0.70733196 0.61605571 0.26035574 0.58168011 0.98663329 0.63217249
 0.57542888 0.56982276 0.92118254 0.68256843 0.67683116 0.52221947
 0.25412134 0.60106127]


0.5121172476898481

13. Создать матрицу с 0 внутри, и 1 на границах

In [92]:
matrixWindow = np.zeros((5,5))
matrixWindow[0,:] = 1
matrixWindow[-1,:] = 1
matrixWindow[:,0] = 1
matrixWindow[:,-1] = 1
matrixWindow

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

14. Создать 5x5 матрицу с 1,2,3,4 под диагональю

In [93]:
matrixsdvig = 1+np.arange(4)
np.diag(matrixsdvig,k=-1)

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

15. Перемножить матрицы 5x3 и 3x2

In [94]:
matrixA = np.arange(15).reshape(5,3)
matrixB = np.arange(6).reshape(3,2)
matrixA.dot(matrixB)

array([[ 10,  13],
       [ 28,  40],
       [ 46,  67],
       [ 64,  94],
       [ 82, 121]])

16. Создать вектор состоящий из 15 элементов, поменять знак у элементов, значения которых между 6 и 12

In [95]:
vec6 = np.arange(15)
np.where((vec6 > 6) & (vec6 < 12), -vec6, vec6)

array([  0,   1,   2,   3,   4,   5,   6,  -7,  -8,  -9, -10, -11,  12,
        13,  14])

17. Создать 2 матрицы A(3x3) и B(3x3), получить матрицу С путем поэлеметного умножения.

In [96]:
matrixA = np.arange(9).reshape(3,3)
matrixB = np.arange(10,19).reshape(3,3)
matrixC = matrixA*matrixB
matrixC

array([[  0,  11,  24],
       [ 39,  56,  75],
       [ 96, 119, 144]])

18. Найти максимальные и минимальные значения матрицы С по строкам и столбцам

In [48]:
matrixA = np.arange(9).reshape(3,3)
print(matrixA)
print(np.max(matrixA, axis = 0))#столбец
print(np.max(matrixA, axis = 1))#строка
print(np.min(matrixA, axis = 0))
print(np.min(matrixA, axis = 1))

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[6 7 8]
[2 5 8]
[0 1 2]
[0 3 6]


19. Создать вектор со значениями от 0 до 1 c 10 наблюдениями

In [97]:
vecNab = np.linspace(0,1,10)
vecNab

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

20. Отсортировать вектор

In [99]:
vec = np.random.random((4,4))
print(vec)
np.sort(vec)

[[0.7810558  0.23076819 0.37239286 0.03846907]
 [0.7558439  0.01620664 0.66220019 0.28947362]
 [0.74502002 0.55690641 0.66115971 0.08967186]
 [0.02556828 0.77960739 0.46726222 0.98487784]]


array([[0.03846907, 0.23076819, 0.37239286, 0.7810558 ],
       [0.01620664, 0.28947362, 0.66220019, 0.7558439 ],
       [0.08967186, 0.55690641, 0.66115971, 0.74502002],
       [0.02556828, 0.46726222, 0.77960739, 0.98487784]])

21. Проверить, одинаковы ли 2 numpy массива

In [100]:
a = np.array([1, 2, 3])
b = np.array([1, 2, 3])
np.array_equal(a, b)

True

22. Сделать массив неизменяемым

In [52]:
arr = np.array([1, 2, 3])
arr.flags.writeable = False
arr[0] = 3

ValueError: assignment destination is read-only

23. Создать случайный вектор из 20 элементов, найти квантиль от 10% и от 80%

In [ ]:
vec8 = np.arange(20)
print(np.quantile(vec8, 0.1))
print(np.quantile(vec8, 0.8))

24. Создать массив любой размерности состоящий из int и string

In [101]:
listing = np.array([1,2,3,"asd"],dtype=object)
listing

array([1, 2, 3, 'asd'], dtype=object)

25. Найти минимальное и максимальное значение, принимаемое каждым числовым типом numpy

In [ ]:
print(np.finfo(np.float64).min)
print(np.iinfo(np.int64).min)

26. Преобразовать массив из float в int

In [102]:
vec9 = np.array([1.2, 3.5])
print(vec9.dtype)
vec9 = vec9.astype(np.int64)
print(vec9.dtype)
vec9

float64
int64


array([1, 3])

27. Отнять среднее из каждой строки в матрице

In [103]:
mat = np.arange(25).reshape(5,5)
print(mat)
mat - np.average(mat)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


array([[-12., -11., -10.,  -9.,  -8.],
       [ -7.,  -6.,  -5.,  -4.,  -3.],
       [ -2.,  -1.,   0.,   1.,   2.],
       [  3.,   4.,   5.,   6.,   7.],
       [  8.,   9.,  10.,  11.,  12.]])

28.

Дана данные из файла.

1,2,3,4,5

6,,,7,8

,,9,10,11

Необходимо прочитать его


In [104]:
import numpy as np
import io

# Исходная строка
str_data = "1,2,3,4,5\
            6,,,7,8\
            ,,9,10,11"

data = np.genfromtxt(io.StringIO(str_data), delimiter=",", dtype=float)
data

array([ 1.,  2.,  3.,  4., nan, nan, nan,  7.,  8., nan,  9., 10., 11.])

29. Посчитайте сумму квадратов натуральных чисел от 1 до 10000.

In [105]:
vector = 1+np.arange(10000)
vector = np.power(vector,2)
vector = np.sum(vector)
vector

333383335000

## BLOKE №2 (tensors)

1. Импортируйте pytorch

In [57]:
import torch

2. Создать вектор состящий из 10 элементов

In [58]:
torch.empty(10)

tensor([2.1707e-18, 7.0952e+22, 1.7748e+28, 1.8176e+31, 7.2708e+31, 5.0778e+31,
        3.2608e-12, 1.7728e+28, 7.0367e+22, 2.1715e-18])

3. Создать тензор из python list

In [59]:
torch.tensor([1, 2, 3, 4, 5])

tensor([1, 2, 3, 4, 5])

4. Создать тензор из np.array

In [60]:
torch.tensor(np.array([1, 2, 3, 4, 5]))

tensor([1, 2, 3, 4, 5])

5. Создать тензор с нормальным распределением

In [61]:
torch.randn(3,3)

tensor([[ 1.3969,  0.8210,  0.1273],
        [-0.2227,  2.6489,  1.2397],
        [ 0.5957, -0.9770,  1.0906]])

6. Создать тензор размером 3х3х3

In [62]:
torch.randn(3,3,3)

tensor([[[ 2.6208, -2.2785, -0.3546],
         [-0.9521, -2.3431,  1.2441],
         [ 2.1441,  1.3255,  0.9831]],

        [[ 1.2452, -0.4214,  1.6674],
         [ 1.6441, -2.0360,  0.8609],
         [ 0.7578,  0.6985, -1.2408]],

        [[ 0.4733,  0.5173,  0.2794],
         [-1.0555,  0.6131,  0.6187],
         [ 0.7231,  0.7123,  2.0867]]])

7. Создать единичную матрицу размером 4х5

In [63]:
torch.eye(4,5)

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.]])

8. Создать вектор размера 25, заполнить елементами со значениме pi

In [64]:
torch.full([25], np.pi)

tensor([3.1416, 3.1416, 3.1416, 3.1416, 3.1416, 3.1416, 3.1416, 3.1416, 3.1416,
        3.1416, 3.1416, 3.1416, 3.1416, 3.1416, 3.1416, 3.1416, 3.1416, 3.1416,
        3.1416, 3.1416, 3.1416, 3.1416, 3.1416, 3.1416, 3.1416])

9. Умножить матрицу размера 9, заполненная от 0 до 8, поэлементно на любое число

In [65]:
A = torch.tensor(np.arange(9).reshape(3,3))
A = torch.multiply(A,3)
print(A)

tensor([[ 0,  3,  6],
        [ 9, 12, 15],
        [18, 21, 24]])


10. Создать произвольный тензор с типом данных int8

In [66]:
torch.tensor([1,2, 3, 4], dtype = torch.int8)

tensor([1, 2, 3, 4], dtype=torch.int8)

11. Изменить тип данных из пункта 10 на int64

In [67]:
torch.tensor([1,2, 3, 4], dtype = torch.int64)

tensor([1, 2, 3, 4])

12. Создать случайный тензор размера 4x5 и найти среднее по 2му столбцу.

In [68]:
A = torch.arange(9).reshape(3,3)
print(A)
torch.mean(A.float(),dim = 0)[1]

tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])


tensor(4.)

13. Создать пустой тензор произвольных размеров

In [69]:
torch.empty(32)

tensor([ 6.3451e-35,  0.0000e+00, -2.0276e+19,  4.5857e-41,  0.0000e+00,
         0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,
         0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,
         0.0000e+00,  1.4013e-45,  0.0000e+00,  0.0000e+00,  0.0000e+00,
         0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,
         0.0000e+00,  0.0000e+00,  0.0000e+00,  1.4013e-45,  0.0000e+00,
        -1.7014e+38,  1.1515e-40])

14. Скалярно умножить 2 вектора

In [106]:
A = torch.randn(3)
B = torch.randn(3)
C = torch.dot(A,B)
C

tensor(1.6524)

15. Умножить матрицу на вектор

In [107]:
A = torch.arange(1,10).reshape(3,3)
B = torch.tensor([1,2,3])
C = torch.matmul(A,B)
print(C)
A

tensor([14, 32, 50])


tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

16. Перемножить 2D матрицы

In [108]:
A = torch.arange(1,10).reshape(3,3)
B = torch.arange(10, 19).reshape(3,3)
C = torch.matmul(A, B)
C

tensor([[ 84,  90,  96],
        [201, 216, 231],
        [318, 342, 366]])

17. Перемножить 3D тензоры

In [109]:
A = torch.arange(27).reshape(3,3,3)
B = torch.arange(27).reshape(3,3,3)
C = torch.matmul(A, B)
C

tensor([[[  15,   18,   21],
         [  42,   54,   66],
         [  69,   90,  111]],

        [[ 366,  396,  426],
         [ 474,  513,  552],
         [ 582,  630,  678]],

        [[1203, 1260, 1317],
         [1392, 1458, 1524],
         [1581, 1656, 1731]]])

18. Создать вектор с нормальным распределением и вывести элементы больше 0.5

In [114]:
A = torch.randn(10)
A[A > 0.5]

tensor([0.9810, 0.8150, 0.5805])

19. Создать матрицу 3х3 заполненную единицами и заменить 1й столбец на 4

In [115]:
A = torch.ones(3,3)
A[: , 0] = 4
A

tensor([[4., 1., 1.],
        [4., 1., 1.],
        [4., 1., 1.]])

20. Создать матрицу и вывести сумму по каждой строке

In [76]:
A = torch.ones(3,3)
torch.sum(A)
torch.sum(A)
torch.sum(A)

tensor(9.)

20. Создать матрицу и вывести среднее по каждому столбцу

In [117]:
A = torch.arange(9).reshape(3,3)
print(A)
torch.mean(A.float(),dim = 0)

tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])


tensor([3., 4., 5.])

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

21. Создать 2 вектора и сконкатенировать по 1 оси

In [78]:
A = torch.arange(4)
B = torch.arange(4)
torch.concat([A,B])

tensor([0, 1, 2, 3, 0, 1, 2, 3])

22. Перемножим две большие единичные матрицы.
Сначал на центральном процессоре, затем попробуйте на GPU

In [79]:
import time

size = 5000


A = torch.ones(size, size, dtype=torch.float32)
B = torch.ones(size, size, dtype=torch.float32)


start = time.time()
C_cpu = torch.matmul(A, B)
end = time.time()
print(f"Время умножения на CPU: {end - start:.4f} сек")


device = "cuda" if torch.cuda.is_available() else "cpu"
print(f"Используем устройство: {device}")

A_gpu = A.to(device)
B_gpu = B.to(device)

start = time.time()
C_gpu = torch.matmul(A_gpu, B_gpu)
torch.cuda.synchronize()
end = time.time()
print(f"Время умножения на GPU: {end - start:.4f} сек")

Время умножения на CPU: 3.9373 сек
Используем устройство: cpu


RuntimeError: Found no NVIDIA driver on your system. Please check that you have an NVIDIA GPU and installed a driver from http://www.nvidia.com/Download/index.aspx