# Home Work 01 
1. Numpy 
1. Pytorch (tensor (basic operations))

# DEADLINE

### IS-142 - 08.10.24 
### IS-141 - 15.10.24

## BLOKE №1 (numpy) 

1. Импортировать NumPy под именем np

In [1]:
import numpy as np

2. Создать вектор (одномерный массив) размера 20, заполненный нулями

In [2]:
vec = np.zeros(20)
print(vec)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


3. Создать вектор размера 20, заполненный числом 1.75

In [3]:
vec1 = np.full(20,1.75)
print(vec1)

[1.75 1.75 1.75 1.75 1.75 1.75 1.75 1.75 1.75 1.75 1.75 1.75 1.75 1.75
 1.75 1.75 1.75 1.75 1.75 1.75]


4. Создать вектор со значениями от 4 до 31

In [4]:
vec3 = np.arange(4,32,1)
print(vec3)

[ 4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27
 28 29 30 31]


5. Развернуть вектор (первый становится последним)

In [5]:
vec4 = np.flip(vec3)
print(vec4)

[31 30 29 28 27 26 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10  9  8
  7  6  5  4]


6. Создать матрицу (двумерный массив) 3x3 со значениями от 1 до 9

In [6]:
matrix = np.arange(1,10,1).reshape(3,3)
print(matrix)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


7. Создать 3x3 единичную матрицу

In [7]:
matrix1 = np.eye(3)
print(matrix1)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


8. Создать 4x4 пустую матрицу

In [8]:
matrix2 = np.empty((4,4))
print(matrix2)

[[ 0.00000000e+000  9.42947026e-308  9.93121735e-306  0.00000000e+000]
 [ 4.94065646e-324  1.38259192e-316  8.00011905e-312  3.43763318e-312]
 [ 2.18141167e-311  4.24399158e-314              nan  8.81442151e-280]
 [-7.45064156e-262  2.41513694e-295  2.22809558e-312  1.04256851e-141]]


9. Создать единичную матрицу 4x4 со сдвигом на единицу вниз относительно главной диагонали

In [9]:
matrixeye = np.eye(4,4,-1)
print(matrixeye)

[[0. 0. 0. 0.]
 [1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]]


10. Создать тензор 3x3x3 со случайными значениями

In [10]:
tens = np.random.random((3,3,3))
print(tens)

[[[0.46108722 0.54108114 0.68838895]
  [0.87803037 0.22978365 0.93394599]
  [0.37315719 0.65895598 0.04337764]]

 [[0.96804911 0.2841296  0.96764976]
  [0.31477757 0.03500489 0.89407476]
  [0.30158478 0.71584269 0.90975691]]

 [[0.43430928 0.71060128 0.09665514]
  [0.13348943 0.58999805 0.96409034]
  [0.64530009 0.72872876 0.72761538]]]


11. Создать массив 5x5 со случайными значениями, найти минимум и максимум

In [11]:
array = np.random.random((5,5))
armin = np.min(array)
armax = np.max(array)
print(array)
print(armin)
print(armax)

[[0.09795927 0.0558392  0.71732542 0.94998672 0.05755041]
 [0.22344657 0.16586288 0.98076077 0.17445402 0.39125618]
 [0.52339832 0.70959424 0.88133789 0.65269371 0.33104367]
 [0.51856197 0.2469374  0.15786567 0.910475   0.99742444]
 [0.57423323 0.17843518 0.27014827 0.66927427 0.02392018]]
0.023920182522582656
0.9974244378701648


12. Создать случайный вектор размера 50 и найти среднее значение всех элементов

In [12]:
vec5 = np.random.random(50)
print(vec5)
midle = np.mean(vec5)
print(midle)

[0.99533898 0.62904976 0.52685502 0.08741345 0.74311827 0.72617605
 0.02814232 0.44392791 0.9234734  0.09465639 0.36528885 0.17342785
 0.43208443 0.34825599 0.7164416  0.33971616 0.11843334 0.68767566
 0.03918062 0.61307278 0.4061093  0.34322846 0.78253091 0.5215633
 0.42080783 0.96827959 0.73688101 0.37919087 0.8375889  0.15235416
 0.05969888 0.04604689 0.27324297 0.62487521 0.38996613 0.37355868
 0.14024721 0.34324931 0.24507555 0.92922888 0.99397306 0.49959072
 0.88527845 0.34866935 0.02421508 0.29577347 0.87402139 0.37292993
 0.31775589 0.4063672 ]
0.4604805480839833


13. Создать матрицу с 0 внутри, и 1 на границах

In [13]:
matrixWindow = np.zeros((5,5))
matrixWindow[0,:] = 1
matrixWindow[-1,:] = 1
matrixWindow[:,0] = 1
matrixWindow[:,-1] = 1
print(matrixWindow)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


14. Создать 5x5 матрицу с 1,2,3,4 под диагональю

In [14]:
matrixsdvig = 1+np.arange(4)
matrixsdvig = np.diag(matrixsdvig,k=-1)
print(matrixsdvig)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


15. Перемножить матрицы 5x3 и 3x2

In [15]:
matrixA = np.arange(15).reshape(5,3)
matrixB = np.arange(6).reshape(3,2)
matrixC = matrixA.dot(matrixB)

16. Создать вектор состоящий из 15 элементов, поменять знак у элементов, значения которых между 6 и 12 

In [16]:
vec6 = np.arange(15)
vec6 = np.where((vec6 > 6) & (vec6 < 12), -vec6, vec6)
print(vec6)

[  0   1   2   3   4   5   6  -7  -8  -9 -10 -11  12  13  14]


17. Создать 2 матрицы A(3x3) и B(3x3), получить матрицу С путем поэлеметного умножения.

In [17]:
matrixA = np.arange(9).reshape(3,3)
matrixB = np.arange(10,19).reshape(3,3)
matrixC = matrixA*matrixB
print(matrixC)

[[  0  11  24]
 [ 39  56  75]
 [ 96 119 144]]


18. Найти максимальные и минимальные значения матрицы С по строкам и столбцам

In [18]:
matrixA = np.arange(9).reshape(3,3)
print(matrixA)
print(np.max(matrixA, axis = 0))#столбец
print(np.max(matrixA, axis = 1))#строка
print(np.min(matrixA, axis = 0))
print(np.min(matrixA, axis = 1))

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[6 7 8]
[2 5 8]
[0 1 2]
[0 3 6]


19. Создать вектор со значениями от 0 до 1 c 10 наблюдениями

In [19]:
vecNab = np.linspace(0,1,10)
print(vecNab)

[0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]


20. Отсортировать вектор

In [20]:
vec = np.random.random((4,4))
print(vec)
print()
vecSort = np.sort(vec)
print(vecSort)

[[0.76300243 0.4485829  0.53415811 0.01379548]
 [0.22418518 0.03931498 0.34115669 0.32579397]
 [0.87667315 0.14384448 0.13512302 0.75787648]
 [0.84940157 0.05901398 0.82728031 0.21100082]]

[[0.01379548 0.4485829  0.53415811 0.76300243]
 [0.03931498 0.22418518 0.32579397 0.34115669]
 [0.13512302 0.14384448 0.75787648 0.87667315]
 [0.05901398 0.21100082 0.82728031 0.84940157]]


21. Проверить, одинаковы ли 2 numpy массива

In [21]:
a = np.array([1, 2, 3])
b = np.array([1, 2, 3])
print(np.array_equal(a, b))

True


22. Сделать массив неизменяемым

In [22]:
arr = np.array([1, 2, 3])
arr.flags.writeable = False 
arr[0] = 3

<class 'ValueError'>: assignment destination is read-only

23. Создать случайный вектор из 20 элементов, найти квантиль от 10% и от 80%

In [23]:
vec8 = np.arange(20)
print(np.quantile(vec8, 0.1))
print(np.quantile(vec8, 0.8))

1.9000000000000001
15.200000000000001


24. Создать массив любой размерности состоящий из int и string

In [24]:
listing = np.array([1,2,3,"asd"],dtype=object)
print(listing)

[1 2 3 'asd']


25. Найти минимальное и максимальное значение, принимаемое каждым числовым типом numpy

In [25]:
print(np.finfo(np.float64).min) 
print(np.iinfo(np.int64).min)

-1.7976931348623157e+308
-9223372036854775808


26. Преобразовать массив из float в int

In [26]:
vec9 = np.array([1.2, 3.5])
print(vec9.dtype)
vec9 = vec9.astype(np.int64)
print(vec9.dtype)
print(vec9)

float64
int64
[1 3]


27. Отнять среднее из каждой строки в матрице

In [27]:
mat = np.arange(25).reshape(5,5)
print(mat)
mat = mat - np.average(mat)
print(mat)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
[[-12. -11. -10.  -9.  -8.]
 [ -7.  -6.  -5.  -4.  -3.]
 [ -2.  -1.   0.   1.   2.]
 [  3.   4.   5.   6.   7.]
 [  8.   9.  10.  11.  12.]]


28. 

Дана данные из файла.

1,2,3,4,5

6,,,7,8

,,9,10,11

Необходимо прочитать его


In [28]:
import numpy as np
import io

# Исходная строка
str_data = "1,2,3,4,5\
            6,,,7,8\
            ,,9,10,11"

data = np.genfromtxt(io.StringIO(str_data), delimiter=",", dtype=float)

print(data)

[ 1.  2.  3.  4. nan nan nan  7.  8. nan  9. 10. 11.]


29. Посчитайте сумму квадратов натуральных чисел от 1 до 10000.

In [29]:
vector = 1+np.arange(10000)
vector = np.power(vector,2)
vector = np.sum(vector)
print(vector)

-1624114088


## BLOKE №2 (tensors) 

1. Импортируйте pytorch

In [56]:
import torch

<class 'ModuleNotFoundError'>: No module named 'torch'

2. Создать вектор состящий из 10 элементов

In [31]:
torch.empty(10)

<class 'NameError'>: name 'torch' is not defined

3. Создать тензор из python list

In [32]:
torch.tensor([1, 2, 3, 4, 5])

<class 'NameError'>: name 'torch' is not defined

4. Создать тензор из np.array

In [33]:
torch.tensor(np.array([1, 2, 3, 4, 5]))

<class 'NameError'>: name 'torch' is not defined

5. Создать тензор с нормальным распределением

In [34]:
torch.randn(3,3)

<class 'NameError'>: name 'torch' is not defined

6. Создать тензор размером 3х3х3

In [35]:
torch.randn(3,3,3)

7. Создать единичную матрицу размером 4х5

In [54]:
torch.eye((4,5))

<class 'NameError'>: name 'torch' is not defined

8. Создать вектор размера 25, заполнить елементами со значениме pi

In [37]:
torch.full([25], np.pi)

9. Умножить матрицу размера 9, заполненная от 0 до 8, поэлементно на любое число

In [38]:
A = torch.tensor(np.arange(9).reshape(3,3))
A = torch.multiply(A,3)
print(A)

10. Создать произвольный тензор с типом данных int8

In [39]:
torch.tensor([1,2, 3, 4], dtype = torch.int8)

11. Изменить тип данных из пункта 10 на int64

In [40]:
torch.tensor([1,2, 3, 4], dtype = torch.int64)

12. Создать случайный тензор размера 4x5 и найти среднее по 2му столбцу.

In [41]:
A = torch.arange(9).reshape(3,3)
print(A)
torch.mean(A.float(),dim = 0)[1]

13. Создать пустой тензор произвольных размеров

In [42]:
torch.empty(32)

14. Скалярно умножить 2 вектора

In [43]:
A = torch.randn(3)
B = torch.randn(3)
C = torch.dot(A,B)
print(C)

15. Умножить матрицу на вектор

In [44]:
A = torch.arange(1,10).reshape(3,3)
B = torch.tensor([1,2,3])
C = torch.matmul(A,B)
print(C)
print(A)

16. Перемножить 2D матрицы 

In [45]:
A = torch.arange(1,10).reshape(3,3)
B = torch.arange(10, 19).reshape(3,3)
C = torch.matmul(A, B)
print(C)
print(A)
print(B)

17. Перемножить 3D тензоры

In [57]:
A = torch.arange(27).reshape(3,3,3)
B = torch.arange(27).reshape(3,3,3)
C = torch.matmul(A, B)
print(C)

<class 'NameError'>: name 'torch' is not defined

18. Создать вектор с нормальным распределением и вывести элементы больше 0.5

In [47]:
A = torch.randn(10)
A[A > 0.5]

19. Создать матрицу 3х3 заполненную единицами и заменить 1й столбец на 4

In [48]:
A = torch.ones(3,3)
A[: , 0] = 4
print(A)

20. Создать матрицу и вывести сумму по каждой строке

In [49]:
A = torch.ones(3,3)
torch.sum(A)
torch.sum(A)
torch.sum(A)

20. Создать матрицу и вывести среднее по каждому столбцу

In [50]:
A = torch.arange(9).reshape(3,3)
print(A)
print(torch.mean(A.float(),dim = 0))

21. Создать 2 вектора и сконкатенировать по 1 оси

In [51]:
A = torch.arange(4)
B = torch.arange(4)
torch.concat([A,B])

22. Перемножим две большие единичные матрицы. 
Сначал на центральном процессоре, затем попробуйте на GPU

In [52]:
import time

size = 5000 


A = torch.ones(size, size, dtype=torch.float32)
B = torch.ones(size, size, dtype=torch.float32)


start = time.time()
C_cpu = torch.matmul(A, B)
end = time.time()
print(f"Время умножения на CPU: {end - start:.4f} сек")


device = "cuda" if torch.cuda.is_available() else "cpu"
print(f"Используем устройство: {device}")

A_gpu = A.to(device)
B_gpu = B.to(device)

start = time.time()
C_gpu = torch.matmul(A_gpu, B_gpu) 
torch.cuda.synchronize() 
end = time.time()
print(f"Время умножения на GPU: {end - start:.4f} сек")